### ISSUE TITLE
When I connect to WSL with SSH with the bottle set up, the Windows executable file cannot be executed

### ISSUE THREAD

**Issue by tsukumijima** [arkane-systems/genie#101]
I have installed sshd on WSL so that I can connect to WSL remotely from another PC.

If you started the sshd service without setting up the bottle, you can run the Windows executable.
(However, if you log in to WSL with SSH, $PATH on the Windows side is not added to the environment variables on the WSL side, so you usually need to execute it with an absolute path.)

Set up the bottle and set the sshd service to start automatically. Then you can SSH login, but you will not be able to run the Windows executable. To be precise, even if you specify an absolute path such as /mnt/c/Windows/System32/cmd.exe, it will exit without outputting anything.

If the bottle is set up, the SSH login seems to automatically go into the bottle (hostname comes with -wsl). This is also the case when you open a new WSL session with the wsl command with the bottle set up.
You can't exit the bottle from inside the bottle, and running exit terminates the SSH session itself, so you can't get out of the bottle.
So I'm not sure if the Windows executable can run if I log in with SSH and get out of the bottle.

Genie was a great tool for me, so it's a shame that when I log in to WSL with SSH I get this problem where I can't run Windows commands.
Would you please fix this issue if possible?

I'm Japanese and use Google Translate. The text may be unnatural.

**Comment by PavelSosin-320** [comment]
Genie doesn't change the fact that WSL is not available outside your computer. It has only a dynamically assigned IP address and no bridge. WSL distro can't work as a real server. There are some tricks and discussions but don't expect that you can use a singleton VM running on OEM Windows Home edition as a team server. You can communicate with WSL VM only from the same Windows Host via its localhost.
Very important thing: Since WSL uses NIC and not Bridge all servers running in WSL distro must listen to 0.0.0.0 address (all interfaces ) instead of 127.0.0.1
P.S. WSL networking is totally crazy.

**Comment by cerebrate** [comment]
@tsukumijima Okay, I've looked into this. The problem that you're seeing isn't actually a genie issue, it's because sshd doesn't pass on environment variables to sessions it starts, so when you log in via ssh, various important variables are missing.  If you look at it with `env`, you should see, for example, that the PATH doesn't include the Windows PATH, and most importantly, the WSL_INTEROP variable is missing, so WSL can't find the proper socket to talk to to make interop work.

But all is not lost. To get these back, we detect when we're running under ssh and can then export them from the systemd environment block and import them in the ssh session. Put this at the _top_ of your profile:

```
if [[ -v SSH_CLIENT ]]; then
  TMPFILE=$(mktemp)
  systemctl show-environment | awk '{print "export "$0}' >> $TMPFILE
  source $TMPFILE
  rm $TMPFILE
fi
```

And you should find that subsequent logins over ssh handle interop correctly.

Thanks for finding this issue! I'll add it to the wiki for future genie users.

**Comment by tsukumijima** [comment]
Thank you for investigating this issue!
I'll give it a try.

**Comment by PavelSosin-320** [comment]
@cerebrate From my experience: To re-enter into the genie bottle I have to enter my distros using wsl -d Ubuntu 20.10 -u desired-user genie -s. But after re-enter the environment looks complete:
root@MSI-wsl-wsl:/mnt/c/Users/Pavel# env
SHELL=/bin/bash
WSL_DISTRO_NAME=Ubuntu-20.10
WT_SESSION=dccb2fad-2374-4691-bf68-ffedae8de50a
NAME=MSI
PWD=/mnt/c/Users/Pavel
USERPROFILE=/mnt/c/Users/Pavel
LOGNAME=root
HOME=/root
LANG=C.UTF-8
**WSL_INTEROP=/run/WSL/3632_interop**
Maybe, SSH session has to start from genie -s instead of bash? Is it possible?

**Comment by cerebrate** [comment]
@PavelSosin-320 

It's just how Linux handles different ways of logging in. `genie -s` uses `machinectl shell` to create a login session inside the bottle, and that does the same thing as _login(1)_ and passes through to the user session the existing system environment that _systemd(1)_ has (i.e., that shown when you run `systemctl show-environment`).

_sshd(1)_ doesn't do that even on vanilla Linux; it sets up its own basic environment when a user logs in over _ssh(1)_, presumably for security reasons. (See the description of the login process on the man page for _sshd(1)_.) This, unfortunately, means that when you log in to WSL/genie with _ssh(1)_, _sshd(1)_ has "helpfully" stripped away all the information you need to have about the WSL/genie environment.

But you don't need to (and, in fact, can't, because you're already inside) reenter the bottle with `genie -s`; you just have to copy back the information that _sshd(1)_ dropped.

**Comment by PavelSosin-320** [comment]
@cerebrate I don't use SSH with WSL, I think this is pathetic - to use SSH for communication with internal VM.
I use Ubuntu and hopefully Fedora soon to run Podman and Podman is CLI. It needs journald and systemd as a default cgroups manager For me, the user environment is essential because Podman work differently in rootfull and rootless  scenario. Easy switch betwee users without su - another-user is issue of convenience.

**Comment by cerebrate** [comment]
It doesn't have to be an internal VM. You know port-forwarding is a one-liner, right? (The same basic one-liner that my Kubernetes cluster uses to allow ingress on any node.)

There are other reasons why you probably wouldn't want to use WSL as a server in production, but setting up remote network access to WSL services is as trivial as forwarding to any other subnet.

Anyway, this is getting off-topic for this issue, so pending the original poster having continued issues with sshd, I'll close this for now.

**Comment by tsukumijima** [comment]
I tried it and it worked fine.
Thank you very much.

**Comment by mkmark** [comment]
> ```
> if [[ -v SSH_CLIENT ]]; then
>   TMPFILE=$(mktemp)
>   systemctl show-environment | awk '{print "export "$0}' >> $TMPFILE
>   source $TMPFILE
>   rm $TMPFILE
> fi
> ```

can be just
```
if [[ -v SSH_CLIENT ]]; then
  export $(systemctl show-environment)
fi
