### ISSUE TITLE
PR: Start Linux kernel with parameters.

### ISSUE THREAD

**Issue by PavelSosin-320** [arkane-systems/genie#109]
There are Crun and Podman requirement to start Kernel with the parameter that enables only the certain cgroups version (V2). 
#https://github.com/containers/podman/issues/9259. It will enable management of the cgroups by systemd both for root and rootless users symmetrically. Currently, after "boot" of the distro using genie -s and subsequent login using genie -l from WT both cgroups V1 and V2 are enabled. It causes an inconsistency because the combined use of cgroups V1 and V2 has some restrictions.
I think that the option can be passed via genie options or genie configuration as it will be more convenient for implementation.
This requirement is valid for Debian as well non-Debian distros.

**Comment by cerebrate** [comment]
genie cannot control the kernel command line or other starting conditions parameters since WSL automatically starts the kernel (shared between distributions) when the first distribution is initialized, before genie or any other Linux-side binary can be run.

However, kernel command line parameters can be configured using the `kernelCommandLine` parameter in .wslconfig, per https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig .
