### ISSUE TITLE
Using genie -i in .bashrc instead of wsl genie -s

### ISSUE THREAD

**Issue by fliespl** [arkane-systems/genie#111]
I have installed systemd genie on my wsl2 ubuntu box.

I wanted to keep starting wsl2 using `wsl` command (without appending genie -s), so I have added: `genie -i` to `.bashrc` file in my user home directory.

I can see that services are starting properly. Is there any drawback to such usage, cause in docs you mention using `wsl genie -s` as proper way.

**Comment by cerebrate** [comment]
`genie -s` leaves you inside the bottle; `genie -i` doesn't.

While the services are running, what this means is that you (your shell) aren't in an environment in which systemd is pid 1, and neither do you share a pid or mount namespace with systemd or any of the services controlled by systemd. Accessing some services can work like this, but things will break unpredictably; it's not a supported/supportable scenario.

The recommended way to have WSL start services and place you inside the bottle automatically is documented here:

https://github.com/arkane-systems/genie/wiki/Automatically-start-genie-on-every-shell-session

**Comment by fliespl** [comment]
Thank you very much for prompt reply and detailed explaination! Appreciate it.

**Comment by fliespl** [comment]
Actually @cerebrate, I would like to follow up. Sorry, if my question is dumb :)

`genie -s` switch doesn't preserve path when logging from windows, so I was thinking about doing it this way:

```
        if [[ ! -v INSIDE_GENIE ]]; then
          exec /usr/bin/genie -c bash
        fi
```

https://github.com/arkane-systems/genie/wiki/%22Open-a-linux-shell%22-and-genie
This example pointed me to this direction, cause I don't want to touch registry in case this solution works.

This lead me to:

```
flies@flies-pc MINGW64 /e/XXX (master)
$ wsl
Waiting for systemd....!
flies@flies-pc-wsl:/mnt/e/XXX$ env
INSIDE_GENIE=true
```

I can see hostname change with suffix -wsl, INSIDE_GENIE variable set and systemd running as pid=1.

Am I still missing something?

**Comment by cerebrate** [comment]
No, doing it that way is fine.

The main difference between `genie -s` and `genie -c bash` is that -s emulates a login, so just like logging in to a regular Linux system, it reads _/etc/passwd_ to determine which shell to run and the home directory you should start in.

-c was designed for quickly running single Linux commands (it's what https://github.com/arkane-systems/RunInGenie uses, for example), so it preserves cwd so that they behave just like Windows commands when it comes to paths, etc. That's pretty much the only significant difference, so using `genie -c bash` to run a shell in the current directory should work fine.

...actually, there's one difference which has to do with how you invoke the shell. `genie -s` emulates a login, so you get a login shell. Just running `genie -c bash` will start a _non-login_ shell, so you might want to use `genie -c bash -l`. The difference is all about which profile scripts run when the shell starts:

A non-login bash will only execute _/etc/bash.bashrc_ and _.bashrc_ when it starts, but;

A login bash will also execute /etc/profile, _.bash_profile_, _.bash_login_, and _.profile_.

So if it looks like you're not seeing all the configuration you should be, this would be why.

**Comment by fliespl** [comment]
@cerebrate that's great! I don't utilize .profile or /etc/profile* paths, so I am good to go.

Thanks again for detailed explaination!

**Comment by PavelSosin-320** [comment]
Genie -s doesn't simulate login, it runs regular systemd boot with activation of all services using their units.  genie -l initializes regular login process. In both cases, systemd  does all the work of creation of root or rootless user slices for the resource management, cgroups and starting networks, and IPC mechanism. In the modern Linux distros nobody knows to do it better than systemd. system-d login daemon starts default user's shell and executes bash profile without any issues.
If you need WT profile for the genie -l login here it ( for Fedora33):
      {
        "guid": "{76ce0607-0119-4bc0-831c-6a367e162f43}",
        "hidden": false,
        "name": "Fedora33Usersession",
        "commandline": "wsl -d Fedora33 genie -l"
      },

**Comment by cerebrate** [comment]
> Genie -s doesn't simulate login, it runs regular systemd boot with activation of all services using their units.

Excuse me, but it does. I wrote that code, and can say that quite definitively.

To summarize:

- `genie -i` boots up a container with systemd. The only reason any of the others appear to be doing this is because they run `genie -i` silently first if you didn't run it manually.
- `genie -s` simulates a login by executing `machinectl shell` . This does all the stuff that /bin/login does - all the PAM, user systemd, login shell, and other interactive user session foo, it does.
- `genie -l` doesn't simulate anything; it creates a TTY and runs a getty on it, which in turn invokes /bin/login. That's why you need to use ^] to get out of the resulting session.
- `genie -c` just runs a command inside the bottle. You get an interactive TTY and a session, but there's no guarantee of the other login session appurtenances.

**Comment by PavelSosin-320** [comment]
@celebrate I use genie -l for login because otherwise The user slice is not created and cgroups mechanism for rootless users doesn't work. I have no idea why plain wsl -u anuser doesn't trigger systemd-logind excursion and genie -l does. When any Dockerless OCI container runner can't find user's slice it crashes. Linux applications also depend on Network and Resolve daemons to resolve to find a DNS server to use.  Without these standard things and their configuration WSL networking doesn't work for me in spite of all Microsofts woodo scripts. Without genie -l DNS names with non-static IP are not resolved correctly in my home network layout.

**Comment by PavelSosin-320** [comment]
Regarding genie -l and wsl -u user-name: execution of bash inside systemd
that has created systemd session and user slice and execution of systemd
inside non-systemd login via wsl -dmydistro  -u myuser results in strange
thing: no new session is created and the user is attached to its own old
session. Maybe logind should work in such a way but it proves that only
genie -l creates a new systemd session. after wsl -u myuser also doesn't
show previous user login history, i.e. it knows nothing about previous
sessions.

**Comment by cerebrate** [comment]
> I have no idea why plain wsl -u anuser doesn't trigger systemd-logind excursion

Because you're outside the bottle. Unless you're inside the bottle, which if you recall is functionally a container using a pid and mount namespace, systemd won't react to anything. And for that matter, `wsl -u <user>` doesn't do anything loginly _outside_ the bottle; in a basic WSL install, there's nothing running to handle one. All it does is create a tty and attach a shell to it under the specified UID. You can test for yourself that none of the PAM modules are invoked.

Anyway, to illustrate the point, this is the state of my system after `wsl genie -s`, starting with WSL stopped:

![image](https://user-images.githubusercontent.com/371623/108563154-a018c100-72c6-11eb-9249-c63981250d8c.png)

Note the user slice, user systemd instance, cgroups, etc., which should be created as standard login behavior. If your system _doesn't_ have these after firing up `wsl genie -s`, that indicates something is wrong with your system configuration; it's not a genie issue.

**Comment by PavelSosin-320** [comment]
Maybe, to clarify the situation it is worst to include _systemctl is-system-running_ into .bashrc script. If the response is "running" then it is definitely an attempt to login to the system bootstrapped by systemd and running. Otherwise - depends on the response.

**Comment by code4lala** [comment]
I found that Konsole, XTerm and UXTerm in KDE desktop can not launch with the following in .bashrc
``` sh
if [[ ! -v INSIDE_GENIE ]]; then
  exec /usr/bin/genie -c bash -l
fi
```

so it may be more suitable for me to add one judgment condition for desktop
``` sh
if [[ ! -v INSIDE_GENIE ]]; then
  if [[ ! -v XDG_CURRENT_DESKTOP ]]; then
    exec /usr/bin/genie -c bash -l
  fi
fi
```

**Comment by Nivethanb** [comment]
Sorry, some one explain how to configure wsl with genie in Ubuntu 22.04
