### ISSUE TITLE
Don't create /sys/fs/cgroup/systemd if /sys/fs/cgroup/unified exists

### ISSUE THREAD

**Issue by PavelSosin-320** [arkane-systems/genie#126]
BUG: It looks like genie creates /sys/fs/cgroup/systemd or causes the creation of /sys/fs/cgroup/systemd in the cases when unified cgroup hierarchy is chosen in the Kernel. It causes 2 unacceptable side effects:

1. Attempt to convert legacy cgroup hierarchy to unified during system boot using systemd 
![image](https://user-images.githubusercontent.com/54495912/110233100-6d0f3800-7f2a-11eb-87a7-36fe34e80f0e.png)

2. misleads Docker and Podman that see the presence of both mounts as a "combined" cgroup setup. The systemd.io strongly recommends not using this setup in the development. [CGoup setup](https://systemd.io/CGROUP_DELEGATION/) Could you check that it doesn't happen on the genie side?

genie --version
Genie 1.36
hostnamectl
 Static hostname: MSI-wsl
       Icon name: computer-container
         Chassis: container
      Machine ID: 051d2c9dfd574a228e61a4776f93258f
         Boot ID: db44d0753e1e4a6e8737e910fbacd409
  Virtualization: wsl
Operating System: Fedora 34 (Container Image Prerelease)
     CPE OS Name: cpe:/o:fedoraproject:fedora:34
          Kernel: Linux 5.4.91-microsoft-standard-WSL2
    Architecture: x86-64
systemctl --version
systemd 248 (v248~rc2-1.fc34)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT **default-hierarchy=unified**

**Comment by cerebrate** [comment]
The handling of cgroups under systemd is negotiated between systemd and the kernel. Genie does nothing to change this process or otherwise touch cgroups in any way; and, in fact, a quick look at /sys/fs/cgroup on a WSL distro _without genie ever having run_ shows that cgroups v1 and v2 are both operating ("hybrid") under WSL before systemd is even brought into it.

_Please_ check the pre-genie state of affairs and/or consult the genie source before filing issues such as this.
