### ISSUE TITLE
[WSL2] Ubuntu 20.04 first run of genie -s results in infinite "Waiting for Systemd.."

### ISSUE THREAD

**Issue by ShadowEO** [arkane-systems/genie#128]
So I've had this issue with my WSL 20.04 instances, the first execution of genie -s results in an infinite waiting on systemd state, however if I open a new tab in Windows Terminal and use genie -s while waiting on it, I get a shell immediately, I'm unsure if there is a race condition going on or something to keep genie from detecting systemd's state, but figured I'd report this.

**Comment by cerebrate** [comment]
As per the README, you have the issue discussed in #110 where certain Ubuntu services cannot start properly in WSL and need tweaking. The second invocation starts immediately because genie waits for system when it initializes the bottle, not when it's just entering it.

**Comment by PavelSosin-320** [comment]
@cerebrate It is not the single reason. I observe constantly the same behaviour but, I believe, due to systemd-networkd-wait-online.service loaded failed
failed Wait for Network to be Configured
The second attempt to enter my Fedora with genie -s or -i is succeeded.
The "slow Network Manager boot" is a very popular topic in the Google search both for Ubuntu and Fedora. It is slow as a turtle on my machine connected via overpopulated WiFi to the overheated in the terms of connected device number WiFi router.  
systemd-analyze blame
_**2min 173ms systemd-networkd-wait-online.service**
     133ms systemd-resolved.service
     110ms systemd-journal-flush.service
     106ms NetworkManager.service
      81ms systemd-logind.service
      81ms systemd-networkd.service
      69ms user@1000.service
      59ms systemd-journald.service
      57ms dev-hugepages.mount
      54ms systemd-homed.service
      40ms user-runtime-dir@1000.service
      35ms user@0.service
      33ms sshd.service
      32ms systemd-userdbd.service
      31ms dbus-broker.service
      26ms dev-mqueue.mount
      25ms sys-kernel-debug.mount
      24ms sys-kernel-tracing.mount
      23ms systemd-tmpfiles-setup.service
      22ms tmp.mount
      21ms modprobe@configfs.service
      21ms modprobe@fuse.service
      21ms modprobe@drm.service
      12ms systemd-sysctl.service
       8ms systemd-update-utmp.service
       7ms systemd-machined.service
       5ms user-runtime-dir@0.service
       5ms systemd-update-utmp-runlevel.service
       5ms systemd-user-sessions.service
       3ms sys-fs-fuse-connections.mount
      87us systemd-homed-activate.service_
But I don't hurry to blame WSL and genie. Without Network Manager WSL networking doesn't work at all. Unfortunately, I didn't find how long it takes for Windows to provide a routable Eth0 interface to WSL, maybe, minutes.
