### ISSUE TITLE
genie -c passing environmental variables

### ISSUE THREAD

**Issue by fliespl** [arkane-systems/genie#132]
Is it possible to do so? Following code doesn't work:
`wsl genie -c 'XYZ=abc env'`

**Comment by cerebrate** [comment]
The thing you have to remember is that `genie -c` invokes the command _directly_, not using an intermediate shell. (As you can see by running `wsl genie -c ps` - you should see the _runinwsl_ helper, _ps_ itself, and maybe a system process like _(sd-pam)_, but no shell.

Setting an environment variable on the command like that is a shell function, which is why it doesn't work. To make it work, you need to explicitly run the command inside a shell, thus:

```
wsl genie -c sh -c 'XYZ=abc env'
```

**Comment by fliespl** [comment]
Thanks again @cerebrate! :)
