### ISSUE TITLE
Error: cannot set terminal process group (-1)

### ISSUE THREAD

**Issue by m-j-r** [arkane-systems/genie#18]
Shell still seems to work, but I'm getting an error message. Perhaps because I'm running a shell via '-c'.

`$ genie -c bash -v`
`genie: outside bottle 247.`
`genie: running command 'bash '`
`bash: cannot set terminal process group (-1): Inappropriate ioctl for device`
`bash: no job control in this shell`

**Comment by cerebrate** [comment]
Hm.

This appears to be an effect of fixing the problem that -c didn't preserve the current working directory. Changing it to use `su(1)` fixed that problem, but it turns out there's some `su(1)` behavior I didn't know about:

https://serverfault.com/questions/411307/cannot-set-terminal-process-group-during-su-to-another-user-as-login-shell

I'll have to think about the best place to go from here. '-s' doesn't use su, FWIW, so it should not cause this issue.

**Comment by m-j-r** [comment]
Seems to me, if we can get to the bottom of #7, then this could probably be closed. Let me know if I can help debug either of these.

**Comment by cerebrate** [comment]
Yeah, that seems like the optimal solution. I've posted a debugging approach over there; let's see what can be done.

**Comment by cerebrate** [comment]
Fixed in 1.7; `runuser` (also in util-linux) is a cut-down `su` that doesn't detach from the controlling terminal, and so doesn't break job control.
