### ISSUE TITLE
Upload `genie-systemd` package to the AUR?

### ISSUE THREAD

**Issue by xuanruiqi** [arkane-systems/genie#184]
**Is your feature request related to a problem? Please describe.**
There is a pre-packaged Arch package hosted here, but usually Arch packages not in the repositories are uploaded to the [AUR](https://aur.archlinux.org/). Particularly, this will allow users to automatically update their package using helper tools like paru or yay when a new release comes out, as opposed to coming here and look for new releases.

**Describe the solution you'd like**
Upload the `genie-systemd` package (or precisely, the PKGBUILD) to the AUR. I can volunteer to help administer the AUR package.

**Describe alternatives you've considered**
Create a repository for this package, but it seems a bit much for a single package.

**Comment by cerebrate** [comment]
It's been tried in the past.

Unfortunately, the AUR maintainers [removed the package](https://lists.archlinux.org/pipermail/aur-requests/2020-September/044860.html) for policy reasons, specifically "this is primarily for use with WSL". Evidently such packages - anything that won't run on vanilla Arch on bare metal - aren't welcome there.

**Comment by xuanruiqi** [comment]
What about a repository for genie? I could also volunteer to maintain that.

**Comment by cerebrate** [comment]
It'd be a much better solution than my ad-hoc packages, certainly. I maintain a similar thing myself for the apt package - and a few  other WSL-centric apt packages - at https://arkane-systems.github.io/wsl-transdebian/ ; there's not one for the other package types just because I know very little about either Arch or Fedora-style packaging.

If you'd be willing to maintain such a thing (and maybe improve my hacked-together PKGBUILD along the way), I'd be very happy for you to do so.

**Comment by xuanruiqi** [comment]
No problem! I'll see what I can do to the PKGBUILD.

**Comment by xuanruiqi** [comment]
Working on a new PKGBUILD. The old PKGBUILD is indeed quite confusing...
