### ISSUE TITLE
Configurable hostname suffix

### ISSUE THREAD

**Issue by skvskv** [arkane-systems/genie#196]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it comes to having multiple distros with genie having same "-wsl" suffix added to hostname. This disables me from distinguishing them by hostname and disallows addressing a particular distro by hostname on my network.

**Describe the solution you'd like**
I'd really love to have an opportunity to configure hostname suffix in the /etc/genie.ini e.g. like the following
![image](https://user-images.githubusercontent.com/7080404/131168878-e2c45a90-1c99-46af-b069-c1514c571656.png)

This would allow having distinct distros addressable by their very own hostname on network like the following:
![image](https://user-images.githubusercontent.com/7080404/131167885-18dc107e-eb14-4c32-8ac8-c51a637dc79b.png)
![image](https://user-images.githubusercontent.com/7080404/131167906-85d4de00-2582-43df-a6a7-2e3ea6303a66.png)

**Describe alternatives you've considered**
I have considered not having multiple distros and this idea upsets me. I have considered having multiple distros having conflicting hostnames on same network and this idea also upsets me.

**Additional context**
I implemented this feature and offer the following PR https://github.com/arkane-systems/genie/pull/195

**Comment by PavelSosin-320** [comment]
This proposal means that so important hostname mechanism of systemd-based Linux will be bypassed. It may be harmful to the Linux kernel and package managers' functionality - package managers may become non-functional or Kernel may crash. To change the static hostname either "canonical", /etc/hostname or hostnamectl --static existing in all modern systemd-based distro shall be used to ensure the correct system behavior. The hostnamed daemon is started as a part of every boot sequence anyway and provides configuration and read API to all programs that need it, like package managers. 
In the WSL environment hostname is hardly usable because all distros reuse the single VM with dynamic IP address, i.e. hostname can't be used for name resolution.

**Comment by cerebrate** [comment]
While I have no problem accepting this PR (contra @PavelSosin-320 , there should be no side-effects from setting arbitrary hostnames for different distros, since every WSL distro runs inside its own [UTS namespace](https://man7.org/linux/man-pages/man7/uts_namespaces.7.html) and _genie_ correctly sets both the kernel hostname and `/etc/hostname` before initializing the bottle) as a potentially useful feature, I must nonetheless offer a caveat:

All WSL distros share a single [network namespace](https://man7.org/linux/man-pages/man7/network_namespaces.7.html); i.e., network interfaces, addresses, sockets, etc., are all shared between distros.

This has a number of implications. One of which, as pointed out above, is that the same IP address is shared between all WSL distros, so while it would allow distros to be addressed by individual hostname, doing so requires the protocol to explicitly differentiate by hostname (as HTTP 1.1 does with the _Host:_ header), as all the hostnames would point to the same IP address.

(A more serious implication is likely to be that running genie/systemd in multiple distros simultaneously is likely to have a large number of issues: since both IP and Unix listening sockets opened in one distro are thus opened in every distro, there may be conflicts or crosstalk, especially since _systemd_ itself relies on several. While it may be possible to make it work, it's an unsupported scenario.)
