### ISSUE TITLE
Bottle problems with split pane terminals

### ISSUE THREAD

**Issue by g0r3** [arkane-systems/genie#200]
**Windows version (build number):**
Windows 10 19043

**Linux distribution:**
Arch Linux (https://github.com/yuk7/ArchWSL)

**Genie version:**
1.44

**Describe the bug**
When starting a Windows Terminal, which creates several panes at startup, only one of the panes will be in the genie bottle

**Confirm that you are running inside the bottle:**
![genie](https://user-images.githubusercontent.com/3685646/132169495-d7c556e9-5671-47ba-89da-d4aad17d4d61.PNG)

**To Reproduce**
Use  genie, Windows Terminal and make it open several panes at startup with in settings.json
"startupActions": "split-pane -s 0.66 -H Arch; split-pane -H Arch"
Most of the time resovable by closing the terminal and reopening a new window.

**Expected behavior**
That all terminal panes would use the bottle

**Additional context**
As stated above. I tried also several methods for waiting for genie in the .zprofile file. What I also noticed, is that the initial genie startup takes very long and most of the time it is not ending by itself. Ctrl-C'ing it and retrying it then make it work immediately, seemingly without problems.
![starting](https://user-images.githubusercontent.com/3685646/132170219-45f369cc-e631-4348-8f35-226109777a20.PNG)

**Comment by therealjojo** [comment]
Probably related to https://github.com/arkane-systems/genie/wiki/Waiting-for-the-user-systemd.

I think what is happening is that the simultaneity of you cascading the windows via terminal all at nearly the same time is not allowing any one instance to have bottled before the others check to see if one is established. The first one (appears) to eventually make it in which would be expected behavior, while the other two drop out on the race condition once the first establishes.

The way I've seen a lot of people solve the problem is by initializing the bottle once through task manager on startup (Create Task with Trigger at log on, create batch script with something like:


```
@echo off
REM Start genie in a hidden window on startup and close bottle established
pwsh -w Hidden -nop -c "&{ wsl genie -i; stop-process -Id $PID }"

REM Close if no errors were produced else stays open for you to debug
if %errorlevel% neq 0 exit /b %errorlevel%

```

and one on restart/shutdown that does makes sure your bottle is fully exited before restart via genie -u.

That way when you engage Terminal, your bottle is already established and they should all successfully enter.

Second option is just building a sleep into your startup action after you trigger the first one to make sure the bottle is established before the second two start.

**Comment by cerebrate** [comment]
Anti-race-condition measures introduced in 1.45, shipping soon, should prevent this.
