### ISSUE TITLE
How to Build Fedora RPM?

### ISSUE THREAD

**Issue by codebam** [arkane-systems/genie#235]
**Linux distribution:**
Fedora

**Describe the bug**
There's no RPM, I want to build one, and this is all I can find. So I don't think I'm able to build it without this?
https://github.com/arkane-systems/genie/blob/master/container-package-fedora.sh#L2

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [ x ] Yes.

**Comment by cerebrate** [comment]
You can ignore that file. That's just used for me building Fedora packages on Debian.

If you look under pending/package/fedora ( https://github.com/arkane-systems/genie/blob/dev-2.2/pending/package/fedora ) you can see the old .spec file for the pre-2.0 genie; if you think you can modify that and the associated Makefile to accommodate the changes in 2.0+ (the Python rewrite) and hook it back up, please do and PR me!

Otherwise, well, Fedora (and Arch) packaging support are on my list and I'll get to it as soon as I can.

(Alternatively, if you grab the dev-2.2 branch, that now supports building a tarball which you should probably be able to use on Fedora.)

**Comment by cerebrate** [comment]
I've got an experimental Fedora package now, built off the 2.2 branch. (Obligatory disclaimer:  _experimental_ .)

If you've got a minute, give it a try?

[genie-2.2-1.fc34.x86_64.rpm.gz](https://github.com/arkane-systems/genie/files/8191528/genie-2.2-1.fc34.x86_64.rpm.gz)

**Comment by icole** [comment]
@cerebrate I just tried that rpm package on a Fedora 35 WSL and it worked great. Thanks a bunch!

**Comment by codebam** [comment]
Works great, thanks!

**Comment by cerebrate** [comment]
Great, thanks for the test. Making the official release now.
