### ISSUE TITLE
`wsl genie -s` not cd to directory as `wsl` would normally do

### ISSUE THREAD

**Issue by mkmark** [arkane-systems/genie#255]
**Is your feature request related to a problem? Please describe.**
`wsl genie -s` not cd to directory as `wsl` would normally do

**Describe the solution you'd like**
`wsl genie -s` cd to directory as `wsl` would normally do

**Describe alternatives you've considered**
`machinectl shell [user]@.host /bin/sh -c 'cd [path]; exec "${SHELL:-sh}"'`

**Additional context**
`subprocess.run("machinectl shell -q " + login + "@.host /bin/sh -c 'cd " + os.getcwd() + "; exec \"${SHELL:-sh}\"'", shell=True)`

**Comment by cerebrate** [comment]
This is by design.

As per https://github.com/arkane-systems/genie/wiki/When-genie-preserves-Windows-environment-variables-and-working-directory , genie -s creates a complete user login session with its own environment, etc., and as such should follow Linux login semantics (i.e., running the user's shell as a login shell, in the user's specified home directory).

To run a shell in the Windows current working directory, use `wsl genie -c /bin/sh`, substituting the path of your preferred shell if it is other than `/bin/sh`.

**Comment by mkmark** [comment]
Thank you! This does clarify the behavior.
Maybe it should be written in the `-h` help message that `-c` preserve cwd, as that is a very important feature for those who like to invoke wsl from the explorer address bar.
I did search 'preserve working directory' before posting the issue, but did not find anything useful because the correct keyword is 'preserve cwd' in wiki XD

**Comment by cerebrate** [comment]
That's a good thought. I'll add that message in 2.4.
