### ISSUE TITLE
Stop the genie process

### ISSUE THREAD

**Issue by ydinot** [arkane-systems/genie#27]
There is command `genie -i` and I want to stop the genie process. How to do that?

**Comment by cerebrate** [comment]
I'm not sure I follow, sorry. The genie process used for initializing the bottle should exit automatically once it's triggered the startup, leaving just unshare/systemd behind.

**Comment by ydinot** [comment]
Sorry if the explanation was not clear. So, actually i want achieve the following scenarios:

1. I want to create prompt info : `user@host (systemd-on)` or `user@host (systemd-off)`
2. First try I just used `genie -i` to initialized then I realized I need to use `genie -s`
3. The problem is I want to exit from systemd process just like before i run `genie -s`

Hope this clears things up

**Comment by arlllk** [comment]
AFAIK you can go back from `genie -s` using `exit` to a environment without genie. But a way to close completely all of systemd with everything that was created maybe can be done using shutdown systemd command, but I'm not sure of that...

**Comment by cerebrate** [comment]
1. The easiest way to check if you're inside the genie bottle, especially for a prompt function, is to check for the existence of the INSIDE_GENIE environment variable:

```
if [[ -v INSIDE_GENIE ]]; then
```

3. Exiting the shell with `exit` will leave systemd and the system services running within the bottle; it may also leave user services running if linger is enabled for the logged-in user (via loginctl). To close down the bottle entirely, you need to shut down the "machine" using

```shutdown -h now```

NOTE: this isn't, strictly speaking, an intended use case, so stopping the bottle like this will leave the "inside-bottle" hostname mounted on /etc/hostname, and it'll need to be dismounted manually. If it isn't, and you make a habit of hopping in and out of the bottle, you'll find that your hostname gets an extra -wsl each time you reenter, thanks to recursive mounting.

(This _may_ be addressed in future versions, but there are several other upgrades before it on the list.)

**Comment by ydinot** [comment]
1. Thanks for the tip
2. I've tried `shutdown -h now` but the problem is WSL become read only FS and I need to shutdown WSL with `wsl --shutdown` and start it again.

I'll close this issue then. Thanks for your heloing

**Comment by cerebrate** [comment]
Just as a final note, this is a bit problematic to implement because systemd (when running as pid 1) isn't really intended to shut down in any way that doesn't shut down the whole machine. (You can see [https://www.freedesktop.org/software/systemd/man/bootup.html#](here) for the gory details, but the important thing is that all the ways of stopping systemd have it replace itself with [https://www.freedesktop.org/software/systemd/man/systemd-halt.service.html#](system-shutdown) which, among other things, tries to unmount all file systems it's aware of and remount root read-only.

(Although, that said, on my usual WSL installation - Debian - the root FS is still read-write outside the bottle after exiting it, so...)

You might be able to remount the WSL root fs read-write with

```
sudo mount -o rw,remount /
```

instead of shutting down and restarting WSL as a whole, though. Hopefully system-shutdown isn't doing anything else that'd break things.
