### ISSUE TITLE
Genie with powerline

### ISSUE THREAD

**Issue by jmauro** [arkane-systems/genie#281]
**Windows version (build number):**
![image](https://user-images.githubusercontent.com/1178356/174500821-ce4f8d95-4cb7-44a7-99ea-be6b1d988a32.png)

**Linux's distribution:**
```
 $ cat /etc/debian_version
bookworm/sid
```

**Kernel version:**
```
cat /proc/sys/kernel/osrelease
5.10.102.1-microsoft-standard-WSL2
```

**Genie version:**
```
$ genie --version
genie 2.3
```

**Describe the bug**
When activating the powerline inside the bottle, the fonts doesn't seem to work:
```
dpkg -l *powerline*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version      Architecture Description
+++-=================-============-============-=================================================
ii  fonts-powerline   2.8.3-1      all          prompt and statusline utility (symbols font)
ii  powerline         2.8.3-1      amd64        prompt and statusline utility
un  powerline-doc     <none>       <none>       (no description available)
ii  python3-powerline 2.8.3-1      all          prompt and statusline utility (Python 3.x module)
```
![image](https://user-images.githubusercontent.com/1178356/174501195-42a0a5b9-ae00-46ef-8ce6-76751800bfa9.png)
Inside the bottle
![image](https://user-images.githubusercontent.com/1178356/174500968-508897d7-54a3-43f8-88dd-96962a1f7ef8.png)

**Expected behavior**
I would expect the following output:
![image](https://user-images.githubusercontent.com/1178356/174501007-50b2e529-dbda-4ea6-9cc1-b855a3f20aba.png)
The current output:
![image](https://user-images.githubusercontent.com/1178356/174501019-b61851df-1174-422b-baa3-f7a3ea0366e1.png)

**Additional context**
I am using the 'Cascadia Code PL' on Windows. I have no idea how to provide more information

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [x] Yes.

**Comment by cerebrate** [comment]
That's a very strange one, since genie shouldn't know or care anything about the font you're using; that should be between Windows and your terminal emulator. And speaking of which, which are you using? Windows Terminal?

(I use Powerline via oh-my-zsh on Debian myself, and can't say I've run into this one.)

**Comment by cerebrate** [comment]
So far, the only way I've found to reproduce a similar behavior (which I found by accident) is on my laptop, in which WSL entered on its own tab shows the PL characters and WSL entered via PowerShell does not. Same goes for sshing into a remote WSL.

The two tabs have identical font and other appearance settings.

(This is mostly a note to self, since it's the closest thing I've found so far.)

**Comment by cerebrate** [comment]
Just to check the obvious, can you send me your TERM environment variable and _stty -a_ output, and whether they differ from outside to inside the bottle?

**Comment by cerebrate** [comment]
Yeah. I don't know what to tell you myself, because as I said, I'm using Powerline on Debian myself and never saw this one. I'll keep looking into it as I have ideas, but unless I can find a repro case...

(Ah. One idea - the most likely possibility is that something systemd is starting is affecting the terminal. Could you send me the output of _both_ `systemctl status` and `systemctl` alone, and I'll see if I can spot anything that might be doing it?)

**Comment by cerebrate** [comment]
Closed as stale.
