### ISSUE TITLE
wslg-xwayland.service & wslg-xwayland.socket does not exist.

### ISSUE THREAD

**Issue by TaivasJumala** [arkane-systems/genie#296]
**Windows version (build number):**
( here the chinese “版本” means version)
WSL 版本： 0.65.3.0
内核版本： 5.15.57.1
WSLg 版本： 1.0.41
MSRDC 版本： 1.2.3213
Direct3D 版本： 1.601.0
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22622.575

**Linux distribution:**
Ubuntu 20.04

**Kernel version:**
5.15.57.1-microsoft-standard-WSL2

**Genie version:**
genie 2.4

**Describe the bug**
According to WSLg FAQ, I'm sure that systemd's default target is set to multi-user.target and installed  pulseaudio-dummy and xwayland-dummy.

Start computer, then open Windows Terminal's Ubuntu-20.04 tab, run 'genie -s'

> sudo systemctl status wslg-xwayland.service

returns

> Unit wslg-xwayland.service could not be found.

which same to wslg-xwayland.socket.

If I don't run genie, wslg work normally. However, after I run it, even after I shutdown genie, wslg will not work poperly.
Mostly reports:
> Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0

**Confirm that you are running inside the bottle:**
inside

**I confirm that I have read the ENTIRE supplied readme file and checked for relevant information on the repository wiki before raising this issue, and that if the solution to this issue is found in either location, it will be closed without further comment:**

 - [x] Yes.

**Comment by cerebrate** [comment]
No, don't do that.

Those services are deprecated and have been removed in recent versions of _genie_ because they essentially cause the problem mentioned in #175. You should have a file _/usr/lib/tmpfiles.d/wslg.conf_ (contents as here: https://github.com/arkane-systems/genie/blob/master/othersrc/usr-lib/tmpfiles.d/wslg.conf ) that automatically recreates the symlink needed for X to work. Do you?

If you don't, create it, restart your WSL instance, and try it again.

If that doesn't work, what's the output of `systemctl status systemd-tmpfiles-setup`?

**Comment by Taivasjumala** [comment]
It's my fault that I could have offer a more detailed bug reproducing steps, but I recently changed to use Ubuntu-22.04, it seems that wslg didn't work well either.

I have checked that `wslg.conf`(Ubuntu-22.04) is in where it should and is the same as the content you gave.

Ubuntu from Microsoft Store, now it should be 22.04

> sudo apt install kubuntu-desktop
(I don't think this matters, both kate&gedit don't work.)

In order to run genie properly in my Ubuntu-22.04, following steps were taken:

> sudo apt-get install -y dotnet-runtime-6.0

then install `genie` from `wsl-transdebain`, and:

> sudo systemctl set-default multi-user.target

`systemd-timeout=5`, I only changed this in `genie.ini`

I have followd @NotTheDr01ds method in [issue#290](https://github.com/arkane-systems/genie/issues/290#issuecomment-1190754016), which is:

> sudo systemctl mask acpid

Do as  @PaulKGrimes said in [issue#266](https://github.com/arkane-systems/genie/issues/266#issuecomment-1128100874),

> kernelCommandLine=systemd.unified_cgroup_hierarchy=1

is added in my .wslconfig, and now my '.wslconfig' is:
>[wsl2]
kernelCommandLine=systemd.unified_cgroup_hierarchy=1


Finally, I deal with `ssh.service`, `systemd-remount-fs.service`, `systemd-sysusers.service` by following the instructions of '[known-problematic systemd units list](https://github.com/arkane-systems/genie/wiki/Systemd-units-known-to-be-problematic-under-WSL)' 

Still, see below
>PS C:\Users\Taiva> wsl --shutdown
PS C:\Users\Taiva> wsl
taivasjumala@OMEN:/mnt/c/Users/Taiva$ cd ~

<hr>

> taivasjumala@OMEN-wsl:~<span>$</span> cat /usr/lib/tmpfiles.d/wslg.conf
\#  This file is part of genie.
\#
>
> <span>#<span> See tmpfiles.d(5) for details
>
> \# Create the needed symlink to make WSLg work under genie.
L+ /tmp/.X11-unix/X0 - - - - /mnt/wslg/.X11-unix/X0
<hr>

>taivasjumala@OMEN:~$ genie -s
Waiting for systemd....!!!
<hr>

> taivasjumala@OMEN-wsl:<span>~</span><span>$</span> genie -r
running
<hr>

> taivasjumala@OMEN-wsl:<span>~</span><span>$</span> genie -b
inside
<hr>

> taivasjumala@OMEN-wsl:<span>~</span><span>$</span> kate
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
>
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, > wayland-xcomposite-glx, xcb.
>
> 已放弃
<hr>

> taivasjumala@OMEN-wsl:/mnt/c/Users/Taiva$ gedit

### It works! Waited a few seconds.
<hr>

> taivasjumala@OMEN-wsl:<span>~</span>$ sudo systemctl status wslg-xwayland.service
> Unit wslg-xwayland.service could not be found.
<hr>

> taivasjumala@OMEN-wsl:~$ firefox
Error: cannot open display: :0

> taivasjumala@OMEN-wsl:~<span>$</span> sudo systemctl status systemd-tmpfiles-setup
● systemd-tmpfiles-setup.service - Create Volatile Files and Directories
     Loaded: loaded (/lib/systemd/system/systemd-tmpfiles-setup.service; static)
     Active: active (exited) since Sat 2022-09-24 12:37:35 CST; 28min ago
       Docs: man:tmpfiles.d(5)
             man:systemd-tmpfiles(8)
    Process: 116 ExecStart=systemd-tmpfiles --create --remove --boot --exclude-prefix=/dev (code=exited, status=0/SUCCE>
   Main PID: 116 (code=exited, status=0/SUCCESS)
>
> 9月 24 12:37:35 OMEN-wsl systemd[1]: Starting Create Volatile Files and Directories...
> 9月 24 12:37:35 OMEN-wsl systemd[1]: Finished Create Volatile Files and Directories.
<hr>

> taivasjumala@OMEN-wsl:<span>~</span>$ exit
注销
> taivasjumala@OMEN:<span>~</span>$ genie -b
outside
taivasjumala@OMEN:<span>~</span>$ genie -r
running (systemd errors)
taivasjumala@OMEN:<span>~</span>$ gedit
> 
> (gedit:957): Gtk-WARNING **: 14:13:20.034: cannot open display: :0
taivasjumala@OMEN:<span>~</span>$ kate
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
>
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
>
> 已放弃

Now genie seems have problems, and gedit now don't work inside bottle
> taivasjumala@OMEN:<span>~</span>$ genie -s
genie: WARNING: systemd is in degraded state, issues may occur!
> taivasjumala@OMEN-wsl:<span>~</span>$ gedit
>
>(gedit:909): Gtk-WARNING **: 14:17:03.773: cannot open display: :0
> taivasjumala@OMEN-wsl:<span>~</span>$ systemctl status systemd-tmpfiles-setup
● systemd-tmpfiles-setup.service - Create Volatile Files and Directories
     Loaded: loaded (/lib/systemd/system/systemd-tmpfiles-setup.service; static)
     Active: active (exited) since Sat 2022-09-24 14:06:59 CST; 14min ago
       Docs: man:tmpfiles.d(5)
             man:systemd-tmpfiles(8)
    Process: 116 ExecStart=systemd-tmpfiles --create --remove --boot --exclude-prefix=/dev (code=exited, status=0/SUCCE>
>   Main PID: 116 (code=exited, status=0/SUCCESS)
>
> 9月 24 14:06:59 OMEN-wsl systemd[1]: Starting Create Volatile Files and Directories...
9月 24 14:06:59 OMEN-wsl systemd[1]: Finished Create Volatile Files and Directories.
> taivasjumala@OMEN-wsl:<span>~</span>$ sudo systemctl status wslg-xwayland.service
[sudo] taivasjumala 的密码：
Unit wslg-xwayland.service could not be found.

What is worse is that, when I want to check if gedit work without genie(it works with `(gedit:39): Gdk-CRITICAL **: 14:41:49.344: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed` ) and do

> wsl --shutdown

to start a fresh new test, my mouse can move around but I can't do anything, so I was forced to restart my laptop hoping my comment was saved(I wrote this in github website).

By the way, I tried Microsoft's systemd yesterday, and I turn it off to do steps above. Meanwhile `wsl --version` differd:
> WSL 版本： 0.67.6.0
内核版本： 5.15.62.1
WSLg 版本： 1.0.44
MSRDC 版本： 1.2.3401
Direct3D 版本： 1.606.4
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows版本： 10.0.22622.601

However, I'm using x410 as x-server. I'm comfortable with that (need some configurations). So using wslg may not that important to me, and with ssh-x11forwading I can do more things like view pdf remotely.

**Comment by Taivasjumala** [comment]
Something I forgot to mention:
As you can see above, `kate` not work both inside and outside after genie started, `gedit` work  inside genie but after exit genie-shell, genie meet errors and don't work. However, both `kate` and `gedit` can work without genie started.
`kate` has warnings:
> kf.kio.core: Malformed JSON protocol file for protocol: "trash" , number of the ExtraNames fields should match the number of ExtraTypes fields
> kf.kio.core: Malformed JSON protocol file for protocol: "trash" , number of the ExtraNames fields should match the number of ExtraTypes fields
> Hspell: can't open /usr/share/hspell/hebrew.wgz.sizes.
> kf.sonnet.clients.hspell: HSpellDict::HSpellDict: Init failed
> kf.sonnet.core: No language dictionaries for the language: "zh_CN" trying to load en_US as default
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
>  "Not connected to D-Bus server"
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
>  "Not connected to D-Bus server"
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
>  "Not connected to D-Bus server"
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
>  "Not connected to D-Bus server"
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
>  "Not connected to D-Bus server"
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
>  "Not connected to D-Bus server"
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
>  "Not connected to D-Bus server"
> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected"
>  "Not connected to D-Bus server"
> Qt: Session management error: networkIdsList argument is NULL
