### ISSUE TITLE
AUR package is missing

### ISSUE THREAD

**Issue by kazigk** [arkane-systems/genie#304]
The [AUR package](https://aur.archlinux.org/packages/genie-systemd-git) mentioned in README is missing.

**Comment by cerebrate** [comment]
Thanks for letting me know.

I don't maintain the AUR version of the package myself, so I'll pass that along. (We've had problems with it being pulled from the AUR before, per #82, #184, etc., so that may have happened again.)

In the meantime, I suggest using the .zst package available from the releases page.
