### ISSUE TITLE
Removes Windows PATH directories

### ISSUE THREAD

**Issue by farzadmf** [arkane-systems/genie#54]
Hi,

I upgraded to WSL 2 today, and I installed `genie-systemd`; it seems to be working perfectly. There's only one issue that I found.

I have configured my Windows Terminal to run `wsl -d ArchLinux genie -s`, however one thing I noticed is that when I do that, I'm not able to run my Windows applications from within my WSL (`PATH` is not updated to contain Windows-related paths).

If I run normally (`wsl -d ArchLinux`), `PATH` is set correctly

**Comment by arlllk** [comment]
[This can workl](https://github.com/arkane-systems/genie/issues/22#issuecomment-531542300)

**Comment by cerebrate** [comment]
Here's the current status of this:

https://github.com/arkane-systems/genie/wiki/A-note-on-environment-variables-and-cwd

In short, _genie -s_ does not preserve the PATH or other environment variables because genie -s reproduces login semantics, which expect systemd/PAM to set up the environment.

genie -c could copy the Windows PATH, but I haven't implemented that yet and have no particular schedule for when I might have time to do it. In the meantime, PRs which merge Windows directories into the inside-bottle path without overwriting it are welcome.
