### ISSUE TITLE
Feature request: logind integration

### ISSUE THREAD

**Issue by ibuildthecloud** [arkane-systems/genie#67]
I don't actually know what logind integration means but the end goal is that I'd like `systemctl --user` commands to work.  Right now they do not work and I suspect that it is because the shell in not running in a proper systemd login context.  Running `loginctl list-users` always returns an empty list.

**Comment by cerebrate** [comment]
So, to confirm, you don't have a `systemd --user` instance running at all, right?

If so, starting that isn't down to genie; that's something the primary _systemd_ is responsible for when PAM tells it someone's logged in or otherwise started a session. Since genie starts shell sessions using _runuser -l_, the relevant file should be (at least on Debian) _/etc/pam.d/runuser-l_. Check that it has a line in it reading:

`-session         optional          pam_systemd.so`

If there isn't, add one, and that should be what you need.

For reference, my /etc/pam.d/runuser-l reads as follows in its entirety, but don't just copy this; your system may be different:

```
#%PAM-1.0
auth            include         runuser
session         optional        pam_keyinit.so force revoke
-session        optional        pam_systemd.so
session         include         runuser
```
