### ISSUE TITLE
First invocation of `genie -s` `systemctl --user` will not work.

### ISSUE THREAD

**Issue by ibuildthecloud** [arkane-systems/genie#70]
This is related to https://github.com/arkane-systems/genie/issues/67.  What I figured out is that if I have a fresh WSL instance and run `genie -s` and then run `systemctl --user list-units` it will fail with

```
$ systemctl --user list-units
Failed to connect to bus: No such file or directory
```
If I exit the shell and then run `genie -s` again it seems to work (sometimes on the third try). It seems to be spotty whether systemd --user gets started. I'm running Ubuntu 20.04 and genie 1.24.

**Comment by cerebrate** [comment]
I think you'll find, if you experiment, that it's not a first-run issue, it's a too-soon issue. Basically, you're running into a race condition that exists because WSL "logins" aren't really logins.

Setting up a login session, complete with _systemd_ user manager instance, etc., is the responsibility of the _systemd-logind_ service; it's got to be up and running before you log in, or none of that happens. On a conventional Linux system, this isn't an issue, because logins go through other _systemd_ services (_getty_, _sshd_, etc.), and _systemd_ unit dependencies prevent any of those services from starting before _systemd-logind_ is ready to provide login sessions.

But WSL "logins" don't go through _systemd_ services, since there isn't any _systemd_ in standard WSL; they're just created by WSL spawning a process in the appropriate environment with the relevant UID. _genie_ simulates a login by using _runuser_ to start a shell within the bottle (which command, `runuser -l`, does trigger the appropriate _systemd-logind_ actions), but it doesn't know when it does this if the _systemd-logind_ within the bottle is running, ready, and capable of doing its job.

(And can't readily have a way to check without making assumptions about the particular distro and configuration that ain't necessarily so. Unless I'm missing something, which is quite possible since I wasn't an expert on the Linux login systems until I started working on _genie_. 😁 )

All of which is to say, if you try to start a shell inside the bottle too quickly after initializing the bottle, you won't get a proper login session because the system won't have finished initializing properly yet. This is _very likely_ to happen, in particular, if you use `genie -s` to initialize the bottle and then start the shell in one (immediately subsequent) operation. Avoiding this issue is one of the things that `genie -i` is for; if you initialize the bottle using it _first_ - say, at Windows login - , allow time for the system _systemd_ to finish initializing, and only then run `genie -s`, and this doesn't happen.

(In retrospect, I probably wouldn't have allowed `genie -s` or `genie -c` to auto-initialize the bottle for you to minimize this particular issue, had I been aware of the race condition at the time, but now that can't be changed without breaking backwards compatibility.)

**Comment by das-rob3rt** [comment]
Noticed the same problem here at my self-baked RHEL 8 distro.

However I noticed that on this system the service `systemd-logind.service` is masked by default. I don't know whether it's related to the fact that this rootfs tarball is actually bootstrapped upon RHUBI 8 image, but I do wonder if things would change if I manually unmask this service.

**Comment by cerebrate** [comment]
Yeah, that would be the issue; systemd-logind is necessary to set up user sessions, and without a user session, there won't be any systemd user instances.

(Unmasking it should fix that, but I can't speak to any other side effects it might have, not knowing why RH masked it in the first place.)
