### ISSUE TITLE
WSL2 detection is not perfect on custom kernels

### ISSUE THREAD

**Issue by evertheylen** [arkane-systems/genie#75]
Hi, I've recently compiled a custom kernel for use with WSL, and was surprised to find that genie no longer works. It gives me the error message "not executing under WSL - how did we get here?". I tracked it down to the [function `IsWsl()`](https://github.com/arkane-systems/genie/blob/d0dabd3ca86965ca0e1da1abd770d40ada687e99/genie/genie/Program.cs#L148) which simply checks for the string "microsoft" in `/proc/sys/kernel/osrelease`. In my custom kernel I changed it to something more descriptive (so I know for sure I'm running my custom kernel and not the standard one).

I found [this thread](https://github.com/microsoft/WSL/issues/4555) in which various ways to detect WSL2 are suggested. The most 'correct' seems to be to check for the directory `/run/WSL`. I can send a PR but wanted to discuss this first. What do you think?

**Comment by cerebrate** [comment]
Yeah, there's not a lot of great options in this space.

(I use a custom kernel myself; my initial compromise was to alter CONFIG_LOCALVERSION from `-microsoft-standard` to `-microsoft-custom` as a differentiator that would still let those scripts, etc., using the [Mm]icrosoft to detect WSL to work. These days I throw in a local identifier and a git stamp, too, but the principle is the same.)

That aside, the major issue I would have with switching to checking for /run/WSL is that that directory is only available under WSL 2. The current code checks for WSL and WSL 2 separately, so that people trying to run genie under WSL 1 get an error message specific to them, and - well, this is something that's happened often enough that I'd prefer not to genericize it.

Hm.

Perhaps a better `IsWsl()` check might be checking for the existence of `WSLInterop` under `/proc/sys/fs/binfmt_misc`, as both WSL 1 and WSL 2 should always have that, and non-WSL systems should not. Would that work with your custom kernel?

**Comment by evertheylen** [comment]
> That aside, the major issue I would have with switching to checking for /run/WSL is that that directory is only available under WSL 2. The current code checks for WSL and WSL 2 separately, so that people trying to run genie under WSL 1 get an error message specific to them, and - well, this is something that's happened often enough that I'd prefer not to genericize it.

I kinda forgot about this, was just focusing on WSL2. Trying to provide helpful error messages is very laudable, definitly the right call.

But wouldn't a bit of logic reordering help? Under WSL1, you can't really customize the kernel, so the check for `microsoft` in `osrelease` should always work. Under WSL2, it may _also_ hold, but we have another 'perfect' check to filter those out. So:

- _IsWsl1_ = 'microsoft' in osrelease and (not _IsWsl2_)
- _IsWsl2_ = '/run/WSL' exists
- _IsWsl_ = _IsWsl1_ or _IsWsl2_

Seems like this will always be correct, unless people like to put 'microsoft' in their custom kernel without actually running WSL.

> Perhaps a better IsWsl() check might be checking for the existence of WSLInterop under /proc/sys/fs/binfmt_misc, as both WSL 1 and WSL 2 should always have that, and non-WSL systems should not. Would that work with your custom kernel?

I only get errors saying `Too many levels of symbolic links` when trying to access `/proc/sys/fs/binfmt_misc`, so I guess not :/

**Comment by cerebrate** [comment]
Turns out WSL can reliably be identified by checking for the type of the root filesystem, so in the end, there's no need to check osrelease at all if we use /run/WSL for WSL 2.

Updated detection now in 1.28.
