### ISSUE TITLE
Path clone fails for Windows paths with spaces

### ISSUE THREAD

**Issue by rathagrimes** [arkane-systems/genie#92]
I encountered the following error:
```
PS C:\Users\Ratha> wsl genie -c emacs 
/usr/libexec/genie/runinwsl.sh: 11: export: Files/Common: bad variable name
```

It looks like, in the script:
`/genie/scripts/runinwsl.sh`
quotes are needed:
```
export PATH="$(echo $PATH | awk -v RS=: '!($0 in a) {a[$0]; printf("%s%s", length(a) > 1 ? ":" : "", $0)}')"
```

**Comment by cerebrate** [comment]
Hm. That's interesting, because I also have - as I suspect is common - a Windows path with a lot of spaces in it, and the script seems to run fine without needing the quotes.

They shouldn't harm anything, so I'll include them in 1.31, but out of curiosity, could you let me know which distribution/release you're using, whether your /bin/sh is a symlink, and if so, what it points to?

**Comment by rathagrimes** [comment]
Thanks for the quick action!

```
$ lsb_release -dc
Description:    Ubuntu 20.04.1 LTS
Codename:       focal
$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jul 18  2019 /bin/sh -> dash*
```
